### ISSUE TITLE
Fix the handling of time for periodic actions

### ISSUE THREAD

**Issue by edgar-bonet** [clovisf/DelayFunction_Substitute_Arduino#1]
In the two .ino sketches in this repository, you wrote:

```c++
  if (time - previousTime < 999990){ // 1 million microsencods= 1 second delay
    /* I have actually used 0.999990 seconds, in a trial to compensate the time that
       this IF function takes to be executed. this is really a point that
       need improvement in my code */   
```

This is indeed not robust: any change in the code (not only within the `if`) will throw off the timings, requiring a re-calibration. Fortunately, the fix is quite easy: instead of updating `previousTime` with:

```c++
previousTime= time;
```

update it with:

```c++
previousTime += task_period;
```

This makes the update independent of the time taken by the code execution. Note that the meaning of `previousTime` is then subtly changed: it is no longer the time when the last action was _performed_, but the time at which that action was _scheduled_.

Example:

```c++
/*
 * Perform an action periodically, without blocking with delay().
 */

const unsigned long print_period = 1000000;  // print every second

unsigned long previous_print_time;

void setup() {
    Serial.begin(9600);
}

void loop() {
    unsigned long now = micros();
    if (now - previous_print_time >= print_period) {
        Serial.print("previous_print_time: ");
        Serial.print(previous_print_time);
        Serial.print(", now: ");
        Serial.println(now);
        previous_print_time += print_period;
    }
}
```

Output:

```text
previous_print_time: 0, now: 1000004
previous_print_time: 1000000, now: 2000000
previous_print_time: 2000000, now: 3000000
previous_print_time: 3000000, now: 4000000
previous_print_time: 4000000, now: 5000000
previous_print_time: 5000000, now: 6000000
previous_print_time: 6000000, now: 7000000
previous_print_time: 7000000, now: 8000000
previous_print_time: 8000000, now: 9000000
previous_print_time: 9000000, now: 10000000
previous_print_time: 10000000, now: 11000004
previous_print_time: 11000000, now: 12000000
```

Notice that the program occasionally gets late by 4&nbsp;µs (presumably because of a timer interrupt), but it catches up at the next iteration. Small timing errors do _not_ accumulate.

You also wrote:

> Notice that the micros() function will overflow every 70 minutes,
> according to this reference: http://arduino.cc/en/reference/micros ; 
> I have not tested the effect of this reset on this code yet (as by
> 10/21/2014).

The approach I am showing here is [rollover-proof](https://arduino.stackexchange.com/a/12588).

**Comment by clovisf** [comment]
Hey, thank you for the fix. I will surely update it, time permitting.

Regards,
*Clovis Fritzen +55(47) 99204-6606*
*https://fritzenlab.com.br <https://fritzenlab.com.br>*
*https://fritzenlab.net <https://fritzenlab.net>*

**Comment by clovisf** [comment]
Code changed according to the idea received
